### ISSUE TITLE
Docker build uses wrong TOR version

### ISSUE THREAD

**Issue by klamann** [brunneis/tor-relay-docker#11]
The recently published docker image with tag `0.4.0.5_x86-64` still uses TOR version `0.3.5.7`.

I've looked into this and figured out that the TOR version is hardcoded in the [Dockerfile](https://github.com/brunneis/tor-relay-docker/blob/77855c843bac1645dea985e4f5be541d6120bab9/tor-relay/x86-64/Dockerfile#L22). Instead, the version in environment variable `$TOR_VERSION` should be used, which is set in [env.sh](https://github.com/brunneis/tor-relay-docker/blob/77855c843bac1645dea985e4f5be541d6120bab9/env.sh), but here is where it gets strange...

I tried to fix this code and submit a quick PR, but I couldn't get it working, because the environment variables were always empty. Well, turns out [you can't access the environemt variables of your shell in Dockerfiles](https://stackoverflow.com/a/34600106), so if we want to make use of the variables in `env.sh`, we should use `ARG` statements in the dockerfile and pass the variables as `--build-arg`s to the docker build call.

However, you could just change the hardcoded TOR version in the Dockerfile and do the proper fix another time ;)

**Comment by brunneis** [comment]
Sorry @klamann, my bad. There are two scripts that have to be executed. First `gen-dockerfiles.sh` in order to generate those "hardcoded" dockerfiles and then `build-arch-images.sh`. Just forgot to execute the first one with the rush.

And yes, I should (and will) refactor the project since there are improvable things to do like using build args as you have noted.

Have a nice day!
